/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:334e5c93-bed9-48b6-aa04-e458d2eb59e1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_hzkFPuTte",
    "aws_user_pools_web_client_id": "2m0j0gq15se8f8gkfkko9r9ebr",
    "oauth": {
        "domain": "scp-kys-ripley.auth.us-east-2.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200",
        "redirectSignOut": "http://localhost:4200/login",
        "responseType": "code"
    }
};


export default awsmobile;
